#!/bin/bash

# Render PostgreSQL Setup Guide
# This script provides commands and guidance for setting up PostgreSQL on Render

echo "🚀 Punjab Rozgar Portal - Render PostgreSQL Setup"
echo "=================================================="

echo ""
echo "📋 Pre-Setup Checklist:"
echo "✅ Render account created"
echo "✅ Frontend deployed on Render"
echo "✅ Backend deployed on Render"
echo "⏳ PostgreSQL database (this guide)"

echo ""
echo "🗄️ Step 1: Create PostgreSQL Database"
echo "--------------------------------------"
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New' → 'PostgreSQL'"
echo "3. Configure:"
echo "   Name: punjab-rozgar-db"
echo "   Database: punjab_rozgar"
echo "   User: (auto-generated)"
echo "   Plan: Free (or preferred)"
echo "   Region: Same as backend service"

echo ""
echo "🔧 Step 2: Get Connection Details"
echo "---------------------------------"
echo "After database creation, copy from Render dashboard:"
echo "📋 Internal Database URL (recommended for backend)"
echo "📋 External Database URL (for external tools)"
echo "📋 Connection parameters (host, port, user, password, database)"

echo ""
echo "⚙️ Step 3: Configure Backend Service"
echo "------------------------------------"
echo "In your backend service environment variables:"
echo "DATABASE_URL=postgresql://user:password@host:5432/database"
echo "SECRET_KEY=your-super-secret-key-here"
echo "ALGORITHM=HS256"
echo "ACCESS_TOKEN_EXPIRE_MINUTES=30"
echo "RENDER=true"
echo "DEBUG=false"
echo "ENVIRONMENT=production"

echo ""
echo "🚀 Step 4: Deploy and Test"
echo "-------------------------"
echo "1. Push code changes to Git repository"
echo "2. Render auto-deploys backend"
echo "3. Monitor deployment logs"
echo "4. Test database connection"

echo ""
echo "✅ Step 5: Verification Commands"
echo "-------------------------------"
echo "Test locally (optional):"
echo "export DATABASE_URL='postgresql://user:password@host:5432/database'"
echo "python health_check.py"
echo ""
echo "Test on Render:"
echo "Check service logs for 'Database connection successful'"

echo ""
echo "🔍 Common PostgreSQL Connection Formats:"
echo "---------------------------------------"
echo "Internal: postgresql://user:pass@host-internal:5432/db"
echo "External: postgresql://user:pass@host-external:5432/db"
echo "Async:    postgresql+asyncpg://user:pass@host:5432/db"

echo ""
echo "📊 Database Features Enabled:"
echo "----------------------------"
echo "✅ Persistent storage"
echo "✅ Concurrent connections"
echo "✅ Automatic backups"
echo "✅ Analytics support"
echo "✅ Full-text search"
echo "✅ JSON columns"
echo "✅ Advanced indexing"

echo ""
echo "🛡️ Security Best Practices:"
echo "---------------------------"
echo "✅ Use Internal URLs for backend connections"
echo "✅ Store credentials in environment variables"
echo "✅ Enable SSL/TLS in production"
echo "✅ Regular security updates"
echo "✅ Monitor access logs"

echo ""
echo "📈 Monitoring & Maintenance:"
echo "---------------------------"
echo "✅ Check Render dashboard for database metrics"
echo "✅ Monitor connection pool usage"
echo "✅ Review slow query logs"
echo "✅ Set up alerts for downtime"
echo "✅ Regular backup verification"

echo ""
echo "🔧 Troubleshooting Tips:"
echo "-----------------------"
echo "❌ Connection refused → Check DATABASE_URL format"
echo "❌ Auth failed → Verify username/password"
echo "❌ Database not found → Check database name"
echo "❌ SSL errors → Add ?sslmode=require to URL"
echo "❌ Pool exhausted → Check connection limits"

echo ""
echo "🎉 Success Indicators:"
echo "--------------------"
echo "✅ Backend logs show 'Database connection successful'"
echo "✅ Health check endpoint returns 200"
echo "✅ User registration works"
echo "✅ Job posting persists data"
echo "✅ No 500 errors in application"

echo ""
echo "📚 Useful Resources:"
echo "------------------"
echo "📖 Render PostgreSQL Docs: https://render.com/docs/databases"
echo "📖 SQLAlchemy AsyncPG: https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.asyncpg"
echo "📖 FastAPI Database: https://fastapi.tiangolo.com/tutorial/sql-databases/"

echo ""
echo "🚀 Ready to proceed? Follow the steps above and then:"
echo "1. Run: python health_check.py"
echo "2. Test your application"
echo "3. Monitor for any issues"
echo ""
echo "Good luck with your deployment! 🎉"